import { Doctor } from "./Doctor.js";
import { Patient } from "./Patient.js";
// ==================== DOCTOR ==================== //
let doctorOne = new Doctor("Rafael da Silva", new Date("1985-01-12 16:10:22"), "145.345.345-34", "Julia Silva", "Carlos da Silva", "Rua Barao", "male", "Clinico Geral", "123456-9");
console.warn("======= DOCTOR =======");
console.log("Name: ", doctorOne.name);
console.log("Birth Day: ", doctorOne.birth);
console.log("CPF: ", doctorOne.cpf);
console.log("Name Mother: ", doctorOne.nameMother);
console.log("Name Father: ", doctorOne.nameFather);
console.log("Address: ", doctorOne.address);
console.log("Genre: ", doctorOne.genre);
console.log("Speciality: ", doctorOne.speciality);
console.log("Medical License: ", doctorOne.medicalLicense);
console.log("Create Message: ", doctorOne.createMessage());
console.log("Edit Message: ", doctorOne.editMessage());
console.log("Delete Message: ", doctorOne.deleteMessage());
doctorOne.name = "Carlos Alberto";
doctorOne.birth = new Date("1977-03-22 06:15:22");
doctorOne.cpf = "115.315.115-11";
doctorOne.nameMother = "Ana Alberta";
doctorOne.nameFather = "Joao Alberto";
doctorOne.address = "Rua 123";
doctorOne.genre = "Male";
doctorOne.speciality = "Cardiologia";
doctorOne.medicalLicense = "123456-12";
console.warn("======= DOCTOR EDITED =======");
console.log("Name: ", doctorOne.name);
console.log("Birth Day: ", doctorOne.birth);
console.log("CPF: ", doctorOne.cpf);
console.log("Name Mother: ", doctorOne.nameMother);
console.log("Name Father: ", doctorOne.nameFather);
console.log("Address: ", doctorOne.address);
console.log("Genre: ", doctorOne.genre);
console.log("Speciality: ", doctorOne.speciality);
console.log("Medical License: ", doctorOne.medicalLicense);
console.log("Create Message: ", doctorOne.createMessage());
console.log("Edit Message: ", doctorOne.editMessage());
console.log("Delete Message: ", doctorOne.deleteMessage());
// ==================== PATIENT ==================== //
let patientOne = new Patient("Sheldon Cooper", new Date("1980-02-26 11:20:55"), "036.869.260-40", "Mary Cooper", "George Cooper", "Av Los Robles Avenue, 2311 Pasadena", "Male");
patientOne.setAppointment(["Appointment 01", "Appointment 02"]);
console.warn("======= PATIENT =======");
console.log("Name: ", patientOne.name);
console.log("Birth Day: ", patientOne.birth);
console.log("CPF: ", patientOne.cpf);
console.log("Name Mother: ", patientOne.nameMother);
console.log("Name Father: ", patientOne.nameFather);
console.log("Address: ", patientOne.address);
console.log("Genre: ", patientOne.genre);
console.log("Appointment: ", patientOne.getAppointment());
console.log("Create Message: ", patientOne.createMessage());
console.log("Edit Message: ", patientOne.editMessage());
console.log("Delete Message: ", patientOne.deleteMessage());
patientOne.name = "Joana da Silva";
patientOne.birth = new Date("1950-12-22 09:10:25");
patientOne.cpf = "502.680.680-54";
patientOne.nameMother = "Julia Garcia";
patientOne.nameFather = "Joao da Silca";
patientOne.address = "Rua 456, Decimal, Numerais";
patientOne.genre = "Female";
patientOne.setAppointment(["Appointment 03", "Appointment 04"]);
console.warn("======= PATIENT EDITED =======");
console.log("Name: ", patientOne.name);
console.log("Birth Day: ", patientOne.birth);
console.log("CPF: ", patientOne.cpf);
console.log("Name Mother: ", patientOne.nameMother);
console.log("Name Father: ", patientOne.nameFather);
console.log("Address: ", patientOne.address);
console.log("Genre: ", patientOne.genre);
console.log("Appointment: ", patientOne.getAppointment());
console.log("Create Message: ", patientOne.createMessage());
console.log("Edit Message: ", patientOne.editMessage());
console.log("Delete Message: ", patientOne.deleteMessage());
